### PR TITLE
Fix example explanation

### PR DESCRIPTION
**Pull request by a-v-l**
Add the wrapping ### to the example

### CODE REVIEW

**Comment by froemken** [comment]
Not tested yet, but in core I found these lines:
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L3159-L3167
It looks like a plain replacement.

I remember the old marker based `###` replacement, but that was called `constants` which was deprecated in TYPO3 12 and removed in TYPO3 13:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.1/Deprecation-99040-DeprecatedTypoScriptSetupConstantsTop-level-object.html#migration

**Comment by froemken** [comment]
Hello @a-v-l 

thank you for your help to make TYPO3 documentation a better place, but I can't merge that patch, as `short` is a plain replacement without old `###` markers. I have just tested it. I think you mixed up it with the good old `parseFunc.constants`

Thank you for your help

Stefan

**Comment by a-v-l** [comment]
Hey @froemken,

thank you for reviewing my pull request. I found the information about `short` in the [TypoScript Reference](https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Parsefunc.html#parsefunc). I haven't tested it myself, but if you are right, the reference is wrong or outdated.

**Comment by froemken** [comment]
Hey @a-v-l 

thank you for that hint. I have created a PR for that here:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/1280

Stefan

**Pull request closed without merging**
